version: '3.7'
services:

  php:
    image: docker.io/nasservb/laravel-php
    volumes:
      - ./:/var/www/
    networks:
      - app-network

      
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    container_name: zookeeper
    volumes:
      - ./zookeeper_data:/bitnami
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network

  kafka:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka
    ports:
      - '9093:9093'
    volumes:
      - ./kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
